### ISSUE TITLE
Showing full tables when adding guest

### ISSUE THREAD

**Issue by Kappeki** [theJovanovic/PubApp#4]
When adding a new guest, and selecting a table for guest to be added, the full tables are shown in the options.
It still wont let the guest to be added to that table.
Just some small "flaw" 

"ZA NADOGRADNJU!"

![image_2024-03-19_004336231](https://github.com/theJovanovic/PubApp/assets/117125171/2f4ef2ce-dde0-449b-aaa6-81d2a3d637ce)

**Comment by theJovanovic** [comment]
uu bravo stavio si i slike

**Comment by theJovanovic** [comment]
Fixed... probably
